### ISSUE TITLE
binary not available for visual studio 2015 on /stable

### ISSUE THREAD

**Issue by pellet** [lasote/conan-libcurl#4]
The binary is downloadable for /ci but not .stable, instead I get this error log:
`libcurl/7.47.1@lasote/stable: Installing package 79ed933823e85f79e98435ad4247ba98d1598dc9
libcurl/7.47.1@lasote/stable: Looking for package 79ed933823e85f79e98435ad4247ba98d1598dc9 in remote 'conan.io'
libcurl/7.47.1@lasote/stable: WARN: Binary for 79ed933823e85f79e98435ad4247ba98d1598dc9 not in remote: Package not found!
ERROR: Can't find a 'libcurl/7.47.1@lasote/stable' package for the specified options and settings
`

**Comment by lasote** [comment]
Hi, could you specify all the used settings? -s xxx -s xxx

**Comment by pellet** [comment]
[requires]
gtest/1.7.0@lasote/stable
FakeIt/2.0.2@hinrikg/stable
libcurl/7.47.1@lasote/ci

[options]
libcurl:shared=True

[generators]
cmake
xcode
visual_studio

[imports]
bin, _.dll -> ./bin
lib, *.dylib_ -> ./bin
., cacert.pem -> ./bin`

I've also had trouble getting a binary for CoreOS when running my tests on a gitlab-ci:

libcurl/7.47.1@lasote/ci: Installing package b8b1901ec75d26797932f87c5c577e7d2fbc0667
libcurl/7.47.1@lasote/ci: Looking for package b8b1901ec75d26797932f87c5c577e7d2fbc0667 in remote 'conan.io' 
libcurl/7.47.1@lasote/ci: WARN: Binary for b8b1901ec75d26797932f87c5c577e7d2fbc0667 not in remote: Package not found!
ERROR: Can't find a 'libcurl/7.47.1@lasote/ci' package for the specified options and settings
- Try to build from sources with "--build libcurl" parameter
- If it fails, you could try to contact the package author  at 'http://github.com/lasote/conan-libcurl', report your configuration and try to collaborate to support it.

Package configuration:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=4.9, os=Linux
- Options: custom_cacert=False, disable_threads=False, shared=True, with_ldap=False, with_openssl=True, OpenSSL:386=False, OpenSSL:no_asm=False, OpenSSL:no_bf=False, OpenSSL:no_cast=False, OpenSSL:no_des=False, OpenSSL:no_dh=False, OpenSSL:no_dsa=False, OpenSSL:no_hmac=False, OpenSSL:no_md2=False, OpenSSL:no_md5=False, OpenSSL:no_mdc2=False, OpenSSL:no_rc2=False, OpenSSL:no_rc4=False, OpenSSL:no_rc5=False, OpenSSL:no_rsa=False, OpenSSL:no_sha=False, OpenSSL:no_sse2=False, OpenSSL:no_threads=False, OpenSSL:no_zlib=False, OpenSSL:shared=True, OpenSSL:zlib_dynamic=False, electric-fence:shared=True, zlib:shared=False

ERROR: Build failed: exit code 1

**Comment by lasote** [comment]
Hi @pellet let me check why are not present those packages. thanks for notice it.

**Comment by lasote** [comment]
Ok, now I remember, Libcurl shared libraries (at least in linux) are having problem with the libefence dependency (from openssl). I can take a look to it and try to solve but it looks hard. Is the static library a valid option for you?

**Comment by lasote** [comment]
Ok, I think I have the fix. The fail with shared is only in Linux x86 systems so should be OK to generate the packages that you need. I'm launching the CI systems and will notice you when its ready.

**Comment by lasote** [comment]
Linux and OSx packages should be ready, please, try it. 
Windows will take a couple of hours to generate all the pacakges.

**Comment by lasote** [comment]
All green! Please, try now with windows and coreos, should be ok (all with lasote/stable channel)

**Comment by pellet** [comment]
thanks so much lasote 👍 works fine on windows now... sorry for taking so long to respond, I had totally forgot I opened this.
